# Generated by Django 2.1 on 2018-08-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Utworzono'),
        ),
    ]
