# Generated by Django 2.1 on 2018-08-20 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_answer_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Utworzono'),
        ),
    ]
